name: Build and deploy Node.js app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          npm install
          CI=false npm run build --if-present
          
      - name: Sync files
        env:
          dest: "stageoma@103.117.212.30:~/public_html/api/"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -avz -e 'ssh -p 55198 -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /.git/ \
            --exclude deploy_key \
            --exclude /.github/ \
            ./ ${{env.dest}}
