name: Build and deploy Node.js app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Sync files
        env:
          dest: "root@host.universalinitiatives.org:/home/cityblock/api.omangom.com"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -avz --usermap=*:cityblock --groupmap=*:cityblock -e 'ssh -p 5767 -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /.git/ \
            --exclude deploy_key \
            --exclude /.github/ \
            ./ ${{env.dest}}
          /usr/bin/pm2 restart api.omangom.com
